### ISSUE TITLE
天地图的API出问题了

### ISSUE THREAD

**Issue by nobody284** [Ren-Chang/SlippyRailMapCn#2]

**Comment by Ren-Chang** [comment]
已修复[f2d4af](https://github.com/Ren-Chang/SlippyRailMapCn/commit/f2d4af78f6a074dae9da8259991c45d6c8b5a6a7)。

目前地形和影像图层添加了[key](http://lbs.tianditu.gov.cn/authorization/authorization.html)，根据公告免费注册并在试运行期间暂无请求限制。行政区划图层修改了天地图的域名暂时恢复，但是[官方文档](http://service.tianditu.gov.cn/pages/info.html?sid=5288&type=info)和[GetCapabilities](http://cite.opengeospatial.org/pub/cite/files/edu/wms/text/operations.html#getcapabilities)的[响应](http://gisserver.tianditu.gov.cn/TDTService/region/wms?service=wms&request=GetCapabilities)里的域名`gisserver.tianditu.com`都已经无法使用了。因此这次修了搞不好什么时候还要坏。
